// urlParam_v2.js
(function(){
  var BASE_URL='https://www.trinks.com/programa-para-salao-de-beleza/cadastrar-meu-estabelecimento/dados-iniciais';
  function setCookie(name,value,days){if(typeof days==='undefined')days=30;var e=new Date();e.setDate(e.getDate()+days);document.cookie=name+'='+String(value||'')+';expires='+e.toUTCString()+';path=/;SameSite=Lax'}
  function getCookie(name){var cs=document.cookie.split(';');for(var i=0;i<cs.length;i++){var c=cs[i].trim();if(c.indexOf(name+'=')===0){return c.substring(name.length+1)}}return null}
  function maybeDecodeURIComponent(str){if(!str)return'';try{var d=decodeURIComponent(str);return d!==str?d:str}catch(e){return str}}
  function readCookieDecoded(n){return maybeDecodeURIComponent(getCookie(n)||'')}
  function normalizeForMatch(u){try{var url=new URL(u,location.origin);var h=url.host.replace(/^www\./,'');var p=url.pathname.replace(/\/+$/,'');return h+p}catch(e){return''}}
  var BASE_MATCH=normalizeForMatch(BASE_URL);
  function initCookies(){if(!getCookie('referrer'))setCookie('referrer',document.referrer||'');if(!getCookie('landingUrl'))setCookie('landingUrl',window.location.href);if(!getCookie('device')){var d=window.innerWidth<768?'mobile':'desktop';setCookie('device',d)}if(!getCookie('firstLandingUrl'))setCookie('firstLandingUrl',window.location.href);if(!getCookie('firstLandingUrlDateTime'))setCookie('firstLandingUrlDateTime',new Date().toISOString())}
  function captureFirstClick(linkHref){if(!getCookie('firstClickUrl'))setCookie('firstClickUrl',linkHref||window.location.href);if(!getCookie('firstClickUrlDateTime'))setCookie('firstClickUrlDateTime',new Date().toISOString());window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:'parametros_blog',event_category:'engagement',event_label:window.location.pathname,referrer:readCookieDecoded('referrer'),landing_url:readCookieDecoded('landingUrl'),device:readCookieDecoded('device'),first_click_url:readCookieDecoded('firstClickUrl'),first_click_datetime:getCookie('firstClickUrlDateTime')||'',first_landing_url:readCookieDecoded('firstLandingUrl'),first_landing_datetime:getCookie('firstLandingUrlDateTime')||''})}
  function urlBuilder(){var p=new URLSearchParams({referrer:readCookieDecoded('referrer'),landingUrl:readCookieDecoded('landingUrl'),dispositivo:readCookieDecoded('device'),firstClickUrl:readCookieDecoded('firstClickUrl'),firstClickUrlDateTime:getCookie('firstClickUrlDateTime')||'',firstLandingUrl:readCookieDecoded('firstLandingUrl'),firstLandingUrlDateTime:getCookie('firstLandingUrlDateTime')||''});return BASE_URL+'?'+p.toString()}
  function interceptAndRedirect(linkHref){captureFirstClick(linkHref);var f=urlBuilder();renderDebugUrl(f);window.location.href=f}
  function renderDebugUrl(u){var el=document.getElementById('parameters');if(!el)return;var f=u||urlBuilder();el.innerHTML='';var p=document.createElement('p');p.textContent='URL de redirecionamento:';var a=document.createElement('a');a.href=f;a.textContent=f;a.rel='noopener noreferrer';a.target='_blank';el.appendChild(p);el.appendChild(a);var pre=document.createElement('pre');pre.style.marginTop='10px';pre.textContent=JSON.stringify({referrer:readCookieDecoded('referrer'),landingUrl:readCookieDecoded('landingUrl'),dispositivo:readCookieDecoded('device'),firstClickUrl:readCookieDecoded('firstClickUrl'),firstClickUrlDateTime:getCookie('firstClickUrlDateTime')||'',firstLandingUrl:readCookieDecoded('firstLandingUrl'),firstLandingUrlDateTime:getCookie('firstLandingUrlDateTime')||''},null,2);el.appendChild(pre)}
  function setupLinkInterceptor(){document.addEventListener('click',function(e){var link=e.target&&e.target.closest?e.target.closest('a'):null;if(!link||!link.href)return;var matches=normalizeForMatch(link.href).startsWith(BASE_MATCH);if(!matches)return;e.preventDefault();interceptAndRedirect(link.href)},true)}
  function migrateDecodingIfNeeded(){['referrer','landingUrl','device','firstLandingUrl','firstClickUrl','firstClickUrlDateTime','firstLandingUrlDateTime'].forEach(function(k){var raw=getCookie(k);if(!raw)return;var looks=/%[0-9A-Fa-f]{2}/.test(raw)||raw.indexOf('+')!==-1;var dec=maybeDecodeURIComponent(raw);if(looks||dec!==raw){setCookie(k,dec)}})}
  function boot(){migrateDecodingIfNeeded();initCookies();setupLinkInterceptor();renderDebugUrl()}
  if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',boot)}else{boot()}
  window.interceptAndRedirect=interceptAndRedirect;
  window.__urlParamDebug__={urlBuilder,renderDebugUrl};
})();
